# Generated by Django 5.0.4 on 2024-05-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='arg_of_pericenter',
            field=models.FloatField(verbose_name='ARG_OF_PERICENTER'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='bstar',
            field=models.FloatField(verbose_name='BSTAR'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='classification_type',
            field=models.CharField(max_length=10, verbose_name='CLASSIFICATION_TYPE'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='eccentricity',
            field=models.FloatField(verbose_name='ECCENTRICITY'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='element_set_no',
            field=models.IntegerField(verbose_name='ELEMENT_SET_NO'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='ephemeris_type',
            field=models.IntegerField(verbose_name='EPHEMERIS_TYPE'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='epoch',
            field=models.DateTimeField(verbose_name='EPOCH'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='inclination',
            field=models.FloatField(verbose_name='INCLINATION'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='mean_anomaly',
            field=models.FloatField(verbose_name='MEAN_ANOMALY'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='mean_motion',
            field=models.FloatField(verbose_name='MEAN_MOTION'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='mean_motion_ddot',
            field=models.FloatField(verbose_name='MEAN_MOTION_DDOT'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='mean_motion_dot',
            field=models.FloatField(verbose_name='MEAN_MOTION_DOT'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='norad_cat_id',
            field=models.IntegerField(verbose_name='NORAD_CAT_ID'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='object_id',
            field=models.CharField(max_length=20, verbose_name='OBJECT_ID'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='object_name',
            field=models.CharField(max_length=100, verbose_name='OBJECT_NAME'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='ra_of_asc_node',
            field=models.FloatField(verbose_name='RA_OF_ASC_NODE'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='rev_at_epoch',
            field=models.IntegerField(verbose_name='REV_AT_EPOCH'),
        ),
    ]
