# Generated by Django 5.0.4 on 2024-05-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_satellite_arg_of_pericenter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='norad_cat_id',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
